server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/userdb
    username: root
    password: Milos.1993
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    #    database-platform: org.hibernate.dialect.MySQL8Dialect -zastarela
    #    database-platform: org.hibernate.dialect.MySQLDialect  -moze i bez
    hibernate:
      ddl-auto: update
  application:
    name: USER-SERVICE
  config:
    import: configserver:http://localhost:9296

zipkin:
  baseUrl: http://localhost:9411
management:
  tracing:
    sampling:
      probability: 1.0


resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED






#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}