server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/walletdb
    username: 
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    #    database-platform: org.hibernate.dialect.MySQL8Dialect -zastarela
    #    database-platform: org.hibernate.dialect.MySQLDialect  -moze i bez
    hibernate:
      ddl-auto: update
  application:
    name: WALLET-SERVICE
  config:
    import: configserver:http://localhost:9296

zipkin:
  baseUrl: http://localhost:9411
management:
  tracing:
    sampling:
      probability: 1.0

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}